
env:
  CACHIX_AUTH_TOKEN: ENCRYPTED[!dcaeae1286059bec7770e082fd6f3ba7688e548b5f652673973329068380578d8cbfa21ab8b19f1532c8a2824b3faf46!]
  # Save some traffic by excluding the full git history
  CIRRUS_CLONE_DEPTH: "1"
  CIRRUS_SHELL: "/bin/bash"
  INPUT_EXTRA_NIX_CONFIG: "sandbox=false\nexperimental-features = nix-command flakes"
  INPUT_INSTALL_OPTIONS: ""
  INPUT_INSTALL_URL: ""
  INPUT_NIX_PATH: ""
  USER: "root"
  PATH: "/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/per-user/$USER/profile/bin:$PATH"

task:
  name: Build Linux amd64
  # Use the maximum timeout. Needed when rebuilding packages on a channel update.
  # timeout_in: 120m

  container:
    # Defined in https://github.com/nix-community/docker-nixpkgs
    # image: nixpkgs/cachix-flakes:nixos-22.05
    image: ubuntu:20.04

  prepare_env_script:
  - apt update
  - apt -y install sudo curl xz-utils
  install_nix_script: ./.ci/install-nix.sh
  install_cachix_script:
  - nix-env -iA cachix -f https://cachix.org/api/v1/install
  prepare_cachix_script:
  - echo $CACHIX_AUTH_TOKEN | cachix authtoken --stdin
  - cachix use nix-community
  - cachix use mic92
  - cachix use nrdxp

  cachix_watch_background_script: while true; do cachix watch-store truelecter || true; done

  build_script:
  - git config --global --add safe.directory "$(pwd)"
  - nix build '.#nixosConfigurations.nas.config.system.build.toplevel' | cachix push mycache
