[stepper_x]
step_pin = "PD4"
dir_pin = "!PD3"
enable_pin = "!PD6"
microsteps = 256
rotation_distance = 40
endstop_pin = "^PC1"
position_endstop = 0
position_max = 235
homing_speed = 50

[stepper_y]
step_pin = "PA15"
dir_pin = "!PA8"
enable_pin = "!PD1"
microsteps = 256
rotation_distance = 40
endstop_pin = "^PC3"
position_endstop = 0
position_max = 235
homing_speed = 50

[stepper_z]
step_pin = "PE2"
dir_pin = "PE3"
enable_pin = "!PE0"
microsteps = 256
rotation_distance = 8
endstop_pin = "^PC0"
position_endstop = 0
position_max = 235

[stepper_z1]
step_pin = "PD11"
dir_pin = "PD10"
enable_pin = "!PD13"
microsteps = 256
rotation_distance = 8

[extruder]
step_pin = "PD15"
dir_pin = "!PD14"
enable_pin = "!PC7"

microsteps = 256
full_steps_per_rotation = 200
gear_ratio = "50:17"

# old_rd * actual / requested
rotation_distance = 21.664
nozzle_diameter = 0.4
filament_diameter = 1.75

heater_pin = "PB3"
sensor_type = "EPCOS 100K B57560G104F"
sensor_pin = "PA1"
control = "pid"

pid_Kp = 21.527
pid_Ki = 1.063
pid_Kd = 108.982
min_temp = 0
max_temp = 250

# Monofilament coPET METALIC
pressure_advance = 0.2105
# Monofilament PLA CHERRY RED
# pressure_advance = 0.2065

[heater_bed]
heater_pin = "PD7"
sensor_pin = "PA2"
sensor_type = "EPCOS 100K B57560G104F"
control = "pid"
pid_Kp = 54.027
pid_Ki = 0.77
pid_Kd = 948.182
min_temp = 0
max_temp = 130

[fan]
pin = "PB7"
hardware_pwm = true
cycle_time = 0.00004

["heater_fan nozzle_fan"]
pin = "PB6"
hardware_pwm = true
cycle_time = 0.00004

#[heater_fan fan2]
#pin = PB5

[mcu]
#serial = "/dev/serial/by-id/usb-Klipper_stm32h743xx_2E0025001651303232383230-if00"
serial = "/dev/ttyAMA0"
restart_method = "command"

[printer]
kinematics = "cartesian"
max_velocity = 300
max_accel = 10_000
max_z_velocity = 5
max_z_accel = 100

[safe_z_home]
home_xy_position = "100, 117.5"
speed = 50
z_hop = 10
z_hop_speed = 5

########################################
# BLTOUCH
########################################

[bltouch]
samples = 3
sensor_pin = "^PC13"
control_pin = "PE5"
speed = 2.0
z_offset = 1.400
x_offset = 34
y_offset = -57
samples_tolerance = 0.01
samples_tolerance_retries = 3

[bed_mesh]
speed = 150
horizontal_move_z = 7
mesh_min = "50, 60"
mesh_max = "200, 170"
probe_count = "5, 3"

########################################
# EXP1 / EXP2 (display) pins
########################################

[board_pins]
aliases = """

    # EXP1 header
    EXP1_1=PC5, EXP1_3=PB1, EXP1_5=PE9,  EXP1_7=PE11, EXP1_9=<GND>,
    EXP1_2=PB0, EXP1_4=PE8, EXP1_6=PE10, EXP1_8=PE12, EXP1_10=<5V>,
    # EXP2 header
    EXP2_1=PA6, EXP2_3=PE7, EXP2_5=PB2, EXP2_7=PC4,   EXP2_9=<GND>,
    EXP2_2=PA5, EXP2_4=PA4, EXP2_6=PA7, EXP2_8=<RST>, EXP2_10=<NC>
"""

# See the sample-lcd.cfg file for definitions of common LCD displays.

########################################
# TMC2209 configuration
########################################

["tmc2209 stepper_x"]
uart_pin = "PD5"
run_current = 0.600
stealthchop_threshold = 999999
#diag_pin =

["tmc2209 stepper_y"]
uart_pin = "PD0"
run_current = 0.600
stealthchop_threshold = 999999
#diag_pin =

["tmc2209 stepper_z"]
uart_pin = "PE1"
run_current = 0.600
stealthchop_threshold = 999999
#diag_pin =

["tmc2209 stepper_z1"]
uart_pin = "PD12"
run_current = 0.600
stealthchop_threshold = 999999
#diag_pin =

["tmc2209 extruder"]
uart_pin = "PC6"
run_current = 0.700
stealthchop_threshold = 999999
#diag_pin =

########################################
# TMC2130 configuration
########################################

#[tmc2130 stepper_x]
#cs_pin = PD5
#spi_software_miso_pin = PE15
#spi_software_mosi_pin = PE13
#spi_software_sclk_pin = PE14
#run_current = 0.800
#stealthchop_threshold = 999999
#diag1_pin = PC1

#[tmc2130 stepper_y]
#cs_pin = PD0
#spi_software_miso_pin = PE15
#spi_software_mosi_pin = PE13
#spi_software_sclk_pin = PE14
#run_current = 0.800
#stealthchop_threshold = 999999
#diag1_pin = PC3

#[tmc2130 stepper_z]
#cs_pin = PE1
#spi_software_miso_pin = PE15
#spi_software_mosi_pin = PE13
#spi_software_sclk_pin = PE14
#run_current = 0.650
#stealthchop_threshold = 999999
#diag1_pin = PC0

#[tmc2130 extruder]
#cs_pin = PC6
#spi_software_miso_pin = PE15
#spi_software_mosi_pin = PE13
#spi_software_sclk_pin = PE14
#run_current = 0.800
#stealthchop_threshold = 999999
#diag1_pin = PC2

#[tmc2130 extruder1]
#cs_pin = PD12
#spi_software_miso_pin = PE15
#spi_software_mosi_pin = PE13
#spi_software_sclk_pin = PE14
#run_current = 0.800
#stealthchop_threshold = 999999
#diag1_pin = PA0
