display_status = { }
pause_resume = { }

[stepper_x]
step_pin = "PC2"
dir_pin = "PB9"
enable_pin = "!PC3"
microsteps = 16
rotation_distance = 40
endstop_pin = "^PA5"
position_endstop = 0
position_max = 235
homing_speed = 50

[stepper_y]
step_pin = "PB8"
dir_pin = "PB7"
enable_pin = "!PC3"
microsteps = 16
rotation_distance = 40
endstop_pin = "^PA6"
position_endstop = 0
position_max = 235
homing_speed = 50

[stepper_z]
step_pin = "PB6"
dir_pin = "!PB5"
enable_pin = "!PC3"
microsteps = 16
rotation_distance = 8
endstop_pin = "^PA7"
position_endstop = 0
position_max = 250

[bltouch]
samples = 3
sensor_pin = "^PB1"
control_pin = "PB0"
speed = 150.0

# Ductinator
# x_offset = 34
# y_offset = -57
# z_offset = 1.400

# Briss Fang 5.0
x_offset = -50
y_offset = -34
z_offset = 3.194

[bed_mesh]
speed = 150
horizontal_move_z = 7
mesh_min = "50, 60"
mesh_max = "200, 170"
probe_count = "5, 3"

[extruder]
max_extrude_only_distance = 100
step_pin = "PB4"
dir_pin = "PB3"
enable_pin = "!PC3"

microsteps = 16
full_steps_per_rotation = 200
gear_ratio = "50:17"

# old_rd * actual / requested

rotation_distance = 21.955
nozzle_diameter = 0.4
filament_diameter = 1.75
heater_pin = "PA1"
sensor_type = "EPCOS 100K B57560G104F"
sensor_pin = "PC5"
control = "pid"
pid_Kp = 21.527
pid_Ki = 1.063
pid_Kd = 108.982
min_temp = 0
max_temp = 255

# Monofilament coPET METALIC
pressure_advance = 0.2105
# Monofilament PLA CHERRY RED
# pressure_advance = 0.2065

[heater_bed]
heater_pin = "PA2"
sensor_type = "EPCOS 100K B57560G104F"
sensor_pin = "PC4"
control = "pid"
pid_Kp = 54.027
pid_Ki = 0.77
pid_Kd = 948.182
min_temp = 0
max_temp = 130

[fan]
pin = "PA0"
#hardware_pwm = true
#cycle_time = 0.01
#kick_start_time = 1.000

[mcu]
serial = "/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0"
restart_method = "command"

[printer]
kinematics = "cartesian"
max_velocity = 300
max_accel = 3_000
max_z_velocity = 5
max_z_accel = 100

[safe_z_home]
home_xy_position = "20, 20"
speed = 50
z_hop = 10
z_hop_speed = 5
