["gcode_macro PAUSE"]
description = "Pause the actual running print"
rename_existing = "PAUSE_BASE"
variable_extrude = 1
gcode = """

  ##### read E from pause macro #####
  {% set E = printer["gcode_macro PAUSE"].extrude|float %}
  ##### set park positon for x and y #####
  # default is your max posion from your printer.cfg
  {% set x_park = printer.toolhead.axis_maximum.x|float - 5.0 %}
  {% set y_park = printer.toolhead.axis_maximum.y|float - 5.0 %}
  ##### calculate save lift position #####
  {% set max_z = printer.toolhead.axis_maximum.z|float %}
  {% set act_z = printer.toolhead.position.z|float %}
  {% if act_z < (max_z - 2.0) %}
      {% set z_safe = 2.0 %}
  {% else %}
      {% set z_safe = max_z - act_z %}
  {% endif %}
  ##### end of definitions #####
  PAUSE_BASE
  G91
  {% if printer.extruder.can_extrude|lower == 'true' %}
    G1 E-{E} F2100
  {% else %}
    {action_respond_info("Extruder not hot enough")}
  {% endif %}
  {% if "xyz" in printer.toolhead.homed_axes %}
    G1 Z{z_safe} F900
    G90
    G1 X{x_park} Y{y_park} F6000
  {% else %}
    {action_respond_info("Printer not homed")}
  {% endif %}
"""

["gcode_macro RESUME"]
description = "Resume the actual running print"
rename_existing = "RESUME_BASE"
gcode = """

  ##### read E from pause macro #####
  {% set E = printer["gcode_macro PAUSE"].extrude|float %}
  #### get VELOCITY parameter if specified ####
  {% if 'VELOCITY' in params|upper %}
    {% set get_params = ('VELOCITY=' + params.VELOCITY)  %}
  {%else %}
    {% set get_params = "" %}
  {% endif %}
  ##### end of definitions #####
  {% if printer.extruder.can_extrude|lower == 'true' %}
    G91
    G1 E{E} F2100
  {% else %}
    {action_respond_info("Extruder not hot enough")}
  {% endif %}
  RESUME_BASE {get_params}
"""

["gcode_macro CANCEL_PRINT"]
description = "Cancel the actual running print"
rename_existing = "CANCEL_PRINT_BASE"
gcode = """

  TURN_OFF_HEATERS
  CANCEL_PRINT_BASE
  END_PRINT
"""

["gcode_macro START_PRINT"]
description = "Commands to run before print"
gcode = """

  G92 E0 ; Reset Extruder
  {% set BED_TEMP = params.BED_TEMP|default(60)|float %}
  {% set EXTRUDER_TEMP = params.EXTRUDER_TEMP|default(190)|float %}
  M140 S{BED_TEMP} ;Start heating bed
  M104 S{EXTRUDER_TEMP} ;Start heating extruder
  G28 ; Home all axes
  ; BED_MESH_CALIBRATE ; Uncomment when installing bltouch
  G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
  G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
  M109 S{EXTRUDER_TEMP} ;Wait for extruder to reach temp before proceeding
  M190 S{BED_TEMP} ;Wait for bed to reach temp before proceeding
  G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
  G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
  G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line
  G92 E0 ; Reset Extruder
  G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
  G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish
"""

["gcode_macro END_PRINT"]
gcode = """

  ; LED_SUCCESS
  {% set max_y = printer.toolhead.axis_maximum.y|float %}
  # Move nozzle away from print while retracting
  M83 ; Relative E
  G91 ; Relative XYZ
  G1 X-2 Y-2 Z+5 E-3 F300
  G90 ; Absolute XYZ
  M82 ; Absolute E
  M104 S0 ; turn off temperature
  M140 S0 ; turn off heatbed
  M106 S50 ; Leave fan running to protect cooling ducts.
  # Present print
  G1 X0 Y210 F3000 ; present print
  # Disable steppers
  M84
"""

["gcode_macro PRESENT_PLATE"]
gcode = """

  {% set posy = printer.toolhead.axis_maximum.y|float %}
  {% set posx = 5.0 %}
  G0 X{posx} Y{posy} F3000
"""

["gcode_macro LOAD_FILAMENT"]
# default_parameter_SPEES = 400
# default_parameter_PRIME_SPEED = 300
gcode = """

  SAVE_GCODE_STATE NAME=__filament__load
  M83
  G1 E5 F75
  G1 E50 F400
  G1 E35 F400
  G1 E20 F300
  G1 E-1 F400
  RESTORE_GCODE_STATE NAME=__filament__load
"""

["gcode_macro UNLOAD_FILAMENT"]
# default_parameter_SPEED = 400
gcode = """

  SAVE_GCODE_STATE NAME=__filament__load
  M83
  G1 E-13 F250
  G1 E17 F250
  G1 E-13 F250
  G1 E17 F250
  G1 E-50 F400
  G1 E-42 F400
  RESTORE_GCODE_STATE NAME=__filament__load
"""

["gcode_macro Level"]
gcode = """

  SCREWS_TILT_CALCULATE
"""

["gcode_macro G29"]
gcode = """

  G28
  BED_MESH_CALIBRATE
"""

# F360 uses M420 to enable bed levelling, we'll treat it like G29.
["gcode_macro M420"]
gcode = """

  G29
"""

["gcode_macro M600"]
gcode = """

  CHANGE_FILAMENT
"""

["gcode_macro M601"]
gcode = """

  CHANGE_FILAMENT
"""

["gcode_macro CHANGE_FILAMENT"]
# default_parameter_RESUME_SPEED = 80
gcode = """

  M117 Change Filament
  PAUSE
  M117
"""
