octoprint_compat = { }
history = { }

[authorization]
force_logins = false
cors_domains = [ "*" ]
trusted_clients = [ "0.0.0.0/0" ]

["power printer"]
type = "gpio"
pin = "gpiochip0/gpio27"
initial_state = "on"
off_when_shutdown = true
restart_klipper_when_powered = true

[file_manager]
enable_object_processing = true
