[moonraker]
src.git = "https://github.com/Arksine/moonraker"
fetch.github = "Arksine/moonraker"

[klipper]
src.git = "https://github.com/Klipper3d/klipper"
fetch.github = "Klipper3d/klipper"

[klipper-screen]
src.git = "https://github.com/jordanruthe/KlipperScreen"
fetch.github = "jordanruthe/KlipperScreen"

# klipper-screen dependency
[python-networkmanager]
src.pypi = "python-networkmanager"
fetch.pypi = "python-networkmanager"

[klipper-led_effect]
src.git = "https://github.com/julianschill/klipper-led_effect"
fetch.github = "julianschill/klipper-led_effect"

[moonraker-telegram-bot]
src.git = "https://github.com/nlef/moonraker-telegram-bot"
src.branch = "development"
fetch.github = "nlef/moonraker-telegram-bot"

[mainsail]
src.git = "https://github.com/mainsail-crew/mainsail"
src.branch = "develop"
fetch.github = "mainsail-crew/mainsail"
