# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[tfenv]
src.git = "https://github.com/tfutils/tfenv"
fetch.github = "tfutils/tfenv"

[transmissionic]
src.git = "https://github.com/6c65726f79/Transmissionic"
fetch.github = "6c65726f79/Transmissionic"

[s5cmd]
src.git = "https://github.com/peak/s5cmd"
fetch.github = "peak/s5cmd"
