# nvfetcher.toml
[manix]
src.git = "https://github.com/mlvzk/manix"
fetch.github = "mlvzk/manix"

[tfenv]
src.git = "https://github.com/tfutils/tfenv"
fetch.github = "tfutils/tfenv"

[s5cmd]
src.git = "https://github.com/peak/s5cmd"
fetch.github = "peak/s5cmd"

[libcamera]
#src.git = "https://github.com/raspberrypi/libcamera"
fetch.github = "raspberrypi/libcamera"
src.manual = "e68e0f1ed2880ea26b5e317f94e2bbd5332e1598"

[libcamera-apps]
#src.git = "https://github.com/raspberrypi/libcamera-apps"
fetch.github = "raspberrypi/libcamera-apps"
src.manual = "6bade0b112aca37fd9762d180203e376867ff09c"

[rtsp-simple-server]
#src.git = "https://github.com/aler9/rtsp-simple-server"
fetch.github = "aler9/rtsp-simple-server"
src.manual = "85ce12199aa324a8399407aac41f8b2fbaad279d"

[moonraker]
src.git = "https://github.com/Arksine/moonraker"
fetch.github = "Arksine/moonraker"

[klipper]
src.git = "https://github.com/Klipper3d/klipper"
fetch.github = "Klipper3d/klipper"

[klipper-screen]
src.git = "https://github.com/jordanruthe/KlipperScreen"
fetch.github = "jordanruthe/KlipperScreen"

[transmissionic]
src.github = "6c65726f79/Transmissionic"
fetch.url = "https://github.com/6c65726f79/Transmissionic/releases/download/$ver/Transmissionic-webui-$ver.zip"

[mainsail]
src.github = "mainsail-crew/mainsail"
fetch.url = "https://github.com/mainsail-crew/mainsail/releases/download/$ver/mainsail.zip"

[rpi-linux]
src.git = "https://github.com/raspberrypi/linux"
fetch.github = "raspberrypi/linux"

[rpi-fw-nonfree]
src.git = "https://github.com/RPi-Distro/firmware-nonfree"
fetch.github = "RPi-Distro/firmware-nonfree"

[rpi-fw-bluez]
src.git = "https://github.com/RPi-Distro/bluez-firmware"
fetch.github = "RPi-Distro/bluez-firmware"

[rpi-fw]
src.git = "https://github.com/raspberrypi/firmware"
fetch.github = "raspberrypi/firmware"
