name: "Build Linux x86_64 configurations"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install Nix
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Init cachix
      uses: cachix/cachix-action@v10
      with:
        name: truelecter
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community,mic92,nrdxp
    - name: Build system for NAS
      run: |
        nix \
          --log-format bar-with-logs \
          --option keep-going true \
          --show-trace \
          build '.#nixosConfigurations.nas.config.system.build.toplevel'
